#ifndef GDSTK_RS_SHIMS_H
#define GDSTK_RS_SHIMS_H
// Text include guard (not #pragma once) because cxx-build copies this file
// into target/.../cxxbridge/crate/gdstk-rs/src/shims.h, producing two
// distinct paths. #pragma once deduplicates by path identity; an #ifndef
// guard deduplicates by macro definition and works across path copies.

#include <cstdint>
#include <memory>

#include "rust/cxx.h"

// Forward-declare the shared struct BoundingBox from the cxx bridge.
// The full definition is generated by cxx-build from lib.rs and becomes
// available via the auto-generated header included in shims.cpp.
namespace gdstk_shim {
struct BoundingBox;
}

namespace gdstk_shim {

// ---- Opaque handles ----
struct LibraryHandle {
    struct Impl;
    std::unique_ptr<Impl> impl;

    LibraryHandle();
    ~LibraryHandle();

    LibraryHandle(const LibraryHandle&) = delete;
    LibraryHandle& operator=(const LibraryHandle&) = delete;
};

struct CellHandle;
struct PolygonHandle;

// ---- Library ----
std::unique_ptr<LibraryHandle> read_gds_shim(rust::Str filename);
uint64_t library_cell_count(const LibraryHandle& handle);
const CellHandle& library_cell_at(const LibraryHandle& handle, uint64_t idx);

// ---- Cell ----
rust::Str cell_name(const CellHandle& cell);
uint64_t cell_polygon_count(const CellHandle& cell);
const PolygonHandle& cell_polygon_at(const CellHandle& cell, uint64_t idx);

// ---- Polygon ----
double polygon_area(const PolygonHandle& poly);
uint32_t polygon_layer(const PolygonHandle& poly);
uint32_t polygon_datatype(const PolygonHandle& poly);
BoundingBox polygon_bbox(const PolygonHandle& poly);
uint64_t polygon_point_count(const PolygonHandle& poly);

}  // namespace gdstk_shim

#endif  // GDSTK_RS_SHIMS_H
